# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d452cbe1112ee5549be1b026f4ffd66c00a99ca22f7d38598f44cec97d6f2473fa0c872bb763540d2434d6e114773cebc4c568083caccc53ce8d823ef0c029

test:
  secret_key_base: c58c0596450b0a8f9598b46c4f0021811ce81183efdad4d42570150842784161605fda3cd04513be9d5039f1d3f7dbe1d197a4cb929713f51a4c4d0dacfee256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
